com:
  caosong:
    raptor:
      uuid:
        datacenterId: 1
        machineId: 1
      jwt:
        secret: 4566123123
        minutes: 10
      log:
        logPath: D://raptor-log
        appName: ${spring.application.name}${server.port}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_rapto?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: sa123
logging:
  level:
    root: INFO
  config: classpath:logback-spring.xml